- name: TF-DEMO | Setup basics on this machine
  hosts: all
  tasks:
    - name: Set Timezone to Amsterdam
      community.general.timezone:
        name: Europe/Amsterdam

    - name: Firewall | Stop FirewallD
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false

    - name: MOTD | Set MOTD
      ansible.builtin.copy:
        dest: /etc/motd
        content: |
          Welcome to the TF-DEMO environment!
          Please follow the guidelines and best practices while using this system.
